version: '3.9'

services:
  api:
    extends:
      file: docker-compose.api.yaml
      service: api

  gateway:
    extends:
      file: docker-compose.gateway.yaml
      service: gateway

  rldp-proxy:
    extends:
      file: docker-compose.proxy.yaml
      service: rldp-proxy

networks:
  ton-network:
    driver: bridge

volumes:
  ton-storage-data:
  shared-temp:

secrets:
  global-config:
    file: ${TON_STORAGE_GLOBAL_CONFIG:?}
