version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - gateway
    networks:
      - ton-network
    ports:
      - '5174:5174'
    volumes:
      - shared-temp:/app/shared-temp
      - ton-storage-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      STORAGE_DAEMON_ADDRESS: '127.0.0.1:5555'
