export const Routes = {
  HOME: '/',
  AUTH: '/auth',
  SEARCH: '/search',
  PROFILE: '/profile',
  USER_INFO: 'user-info',
  ADD_MANAGER: 'add-manager',
  ALL_MANAGERS: 'all-managers',
  CERTIFICATE_INFO: 'certificate-info',
  ORGANIZATION_INFO: 'organization-info',
  MY_ORGANIZATION: 'my-organization',
  ALL_CERTIFICATES: 'all-certificates',
  MINT_CERTIFICATE: 'mint-certificate',
  CREATE_ORGANIZATION: 'create-organization',
  ORGANIZATION_CERTIFICATES: 'organization-certificates',
  ADD_ORGANIZATION_MANAGER: 'add-organization-manager',
} as const
